#!/usr/bin/env python3

# Created By: Jake@Linux
# Created On: Wed 09 Aug 2023 08:58:57 PM CDT
# Project: 

import random
j = 10
q = 10
k = 10
a = [1, 11]




card_values = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'j', 'q', 'k', 'a']
deck = card_values * 4

print('Let\'s play ciards!')

player_cards = []
dealer_cards = []

while (len(player_cards) != 2):
    card = random.choice(deck)
    deck.remove(card)
    player_cards.append(card)

while (len(dealer_cards) != 2):
    card = random.choice(deck)
    deck.remove(card)
    dealer_cards.append(card)

print(f'Players hand: {player_cards}')

for i, num in enumerate(dealer_cards):
    if i == 0:
        print("Dealers hand: [#", end=", ")
    else:
        print(f'{num}]')


